### ISSUE TITLE
Creación de método para la construcción del Json con la parametrización de formulario y tipos de entradas  

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_mid#12]
Se debe crear un método que reciba como parámetro de consulta el Id de un formato de un plan, consultar la estructura del árbol del formato, recorrer el árbol e ir creado un arreglo de objetos JSON con la estructura para el cliente y la definición de los campos requeridos en el formulario, este arreglo de objetos Json se devuelve en el response de la función creada, se suguiere un método get, la issue debe cumplir con los siguientes requerimientos:

 

- [x] El método debe recibir como parámetro de consulta el id de un formato de plan 
- [x] El método debe extraer la estructura del árbol formato 
- [x] El método debe crear un arreglo de objetos Json con un objeto para la estructura del formulario con los parámetros necesarios ( type y requerido se encuentra en la tabla subgrupo_detalle)
- [x] Devolver el arreglo en el response del método ciñéndose a los lineamientos de la oficina

**Comment by ndmc98** [comment]
Se inicia la issue el 30/08/2021

**Comment by ndmc98** [comment]
De acuerdo a las tareas de la issue:

El método recibe como parámetro el ID del plan.
El método extrae la estructura del árbol.
El retorno del método es un array con dos arrays. En la posición cero [0] se encuentra como tal el árbol de objetos JSON con los campos _id, nombre, type y required_ correspondientes a los subgrupos del plan solicitado. En la posición uno [1] se encuentra el JSON con los identificadores de los campos (id de los subgrupos) que serán requeridos por el formulario dinámico del cliente.

**Comment by ndmc98** [comment]
Para las pruebas del método:

Endpoint con id de prueba: v1/formato/6127b152d40348302338c920

Resultado: 

![image](https://user-images.githubusercontent.com/24207969/132243345-65a0c83e-9b28-46c6-bff1-5a0df522228d.png)

**Comment by ndmc98** [comment]
Se da por finalizada la issue con el respectivo Pull Request

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
