### ISSUE TITLE
Análisis y creación de función mid para el proceso de clonado de planes y registros de planes de acción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_mid#13]
Se debe realizar un analisis para establecer cual es el mejor algoritmo para la implmentación de una función que clone un formato de un plan (estructura del arbol base con los registros de la tabla subgrupo_detalle vacio, esta opción se debe analizar), esta función debe recibir como parametros de entrada aparte del formato base, los varoes de los campos vigencia y dependencia_id de la tabla plan, una vez creado el nuevo arbol base se debe tambien analizar como integrar la función dinamica para la construcción del formulario ya implementado, una vez analizado realizar el desarrollo de la función para el registro de la información de cada rama del arbol, teniendo en cuenta el json entregado por el componente del cliente, la issue debe cumplir con los siguientes requerimientos :

- [x] Analizar el mejor algoritmo para la implementación de la función de clonar el arbol a partir de un formato con los parametros mencionados 
- [x]  Analizar la intregración del algoritmo con la función de la creación de los objetos necesarios para el componente dinamico en el cliente (tener presente que se debe realizar el registro de la información para cada campo en el plan para cada dependecia)
- [x] Implementar la función con lo requerimientos mencionados

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se crea el controlador formulación en planeacion_mid para allí desarrollar la función de clonado de planes. Se utilizo una petición diferente para hacer el post al crud debido a que la función SendJson utilizada en la OAS no funciona con el api crud en NestJs. Se finalizó el desarrollo de la función sin ningún otro inconveniente, salvo el  mencionado anteriormente.

**Comment by brayaned** [comment]
Endpoint para utilizar el controlador: v1/formulacion/clonar_formato/:id

Esta función POST debe recibir en un JSON los siguientes parámetros:

```
{
"vigencia": "Vigencia I",
"dependencia_id": "idPrueba Dependencia"
}
```
La respuesta de esta función es el JSON del clon de plan.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
