### ISSUE TITLE
Ajustar métodos a nivel de mid y crud para el campo observación teniendo en cuenta los estados de los planes

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_mid#18]
Se debe ajustar los métodos de construcción a nivel de mid y crud para el análisis realizado de la construcción del componente dinámico  con el campo de observación teniendo en cuenta el estado del plan, la issue debe cumplir con los siguientes requerimientos: 

- [x] Realizar el ajustes a los métodos correspondientes para poder construir el campo de observación

**Comment by ndmc98** [comment]
Se dio inicio a la issue el 23/09/2021

**Comment by ndmc98** [comment]
Se presentó el análisis y con base en los comentarios se realizó un breve ajuste para mostrar el campo observación según estado en la función _formato_ del MID.

**Comment by ndmc98** [comment]
Se realizan pruebas para validar la construcción del campo _observación_ al llamar al _formato_ según el estado del plan.

Se crea campo observación:

![image](https://user-images.githubusercontent.com/24207969/134839347-7427383e-78c8-4461-8c4f-13c7da49d5cc.png)

No se crea campo observación:

![image](https://user-images.githubusercontent.com/24207969/134839419-96fbdc57-0b96-478a-978a-00d2ac911e13.png)

**Comment by ndmc98** [comment]
Se finaliza el ajuste de la issue con el respectivo Pull Request

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
