### ISSUE TITLE
Implementación de metodos para guardar (post) y consulta (get) para los planes.

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_mid#19]
Se debe desarrollar  los métodos las las funcionalidad de guardar (planes) y la consulta de la información registrada en la tabla de subgrupo_detalle, estos métodos deben recibir desde el cliente el json con todo el arbol de información y el id del plan a guardar, este json trae con sigo el identificador de subgrupo y se debe incluir la información en el detalle_subgripo, para el método de consulta debe recibir el id de plan de consulta y devolver la información con la estructura necesaria para que el componente dinámico construya el plan y muestre la información solicitada, la  issue debe cumplir con los siguientes requerimientos:

- [x] Desarrollar la funcionalidad para guardar los planes con el flujo mencionado
- [x] Desarrollar la funcionalidad para consultar los planes con el flujo mencionado

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
Se realizó la función post para guardar la información enviada por el cliente, para esto se modifico la tabla subgrupo-detalle en el crud. A esta tabla se le agregó el campo dato-plan y es allí donde se guardara la información de todas las actividades.

**Comment by brayaned** [comment]
El body que recibe la función GuardarActividad() del mid es el siguiente:

```
{"6139894fdf020f41fc56e5af":"",
"613991a6df020f6a5556e5b7":1,
"613991d1df020ff74556e5c2":"Prueba Meta segplan",
"613991e3df020f680656e5cf":"Prueba tipo meta",
"613991f4df020fd61956e5de":"Prueba descripcion meta",
"61399208df020f3fea56e5ef":"prueba formula del indicador",
"613acf8edf020f82a056eb2b":"",
"613ad17adf020f2d0f56eb70":"",
"613ad189df020f10fb56eb85":"",
"613ad1a3df020f474756ebb0":"",
"613ad1b4df020f3f0d56ebc9":"prueba 2023",
"613ad1cfdf020f4e0156ebe4":"Formulacion 2020",
"613ad1eadf020f305a56ec01":"Prueba programacion 2020",
"613ad203df020f799a56ec20":"ejecucion 2020",
"613ad21adf020f6fc156ec41":"formulacion 2021",
"613ad21adf020f6fc156ec41_o":"OBSERVACION PRUEBA",
"613ad22fdf020fd90856ec78":"programacion 2021",
"613ad247df020f2ea656ec9d":"formualcion 2022",
"613ad25cdf020fd15156ecc4":"programacion 2022 PRUEBA",
"613ad46edf020fed5256edd8":"",
"613adb88df020fdb1e56edfe":"",
"613adb9cdf020f00f656ee29":"formulacion 2021",
"613adbcadf020f74af56ee56":"",
"613adc09df020f83dd56ee8a":2,
"613b4b71df020f6c0456f06f":"programacion 2023",
"613b4cf0df020f4f1156f19f":"ejecucion 2022",
"6139894fdf020f41fc56e5afo":"",
"613991a6df020f6a5556e5b7o":"",
"613991d1df020ff74556e5c2o":"",
"613991e3df020f680656e5cfo":"",
"613991f4df020fd61956e5deo":"",
"61399208df020f3fea56e5efo":"",
"613acf8edf020f82a056eb2bo":"",
"613ad17adf020f2d0f56eb70o":"",
"613ad189df020f10fb56eb85o":"",
"613ad1a3df020f474756ebb0o":"",
"613ad1b4df020f3f0d56ebc9o":"",
"613ad1cfdf020f4e0156ebe4o":"",
"613ad1eadf020f305a56ec01o":"",
"613ad203df020f799a56ec20o":"",
"613ad21adf020f6fc156ec41o":"",
"613ad22fdf020fd90856ec78o":"",
"613ad247df020f2ea656ec9do":"",
"613ad25cdf020fd15156ecc4o":"",
"613ad46edf020fed5256edd8o":"",
"613adb88df020fdb1e56edfeo":"",
"613adb9cdf020f00f656ee29o":"",
"613adbcadf020f74af56ee56o":"",
"613adc09df020f83dd56ee8ao":"",
"613b4b71df020f6c0456f06fo":"",
"613b4cf0df020f4f1156f19fo":""}
```
Por cada una de las keys del json se especifica cual va a ser el campo dato de cada una de las actividades, estas actividades pertenecen a un subgrupo especifico.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
