### ISSUE TITLE
Crear flujo para el cambio de estado del plan de acción 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_mid#20]
Se debe desarrollar el flujo para realizar los cambios de estado en los planes que ya se encuentren asignados, para el caso cuando se agrega la primera actividad u otra actividad se debe cambian de estado de no tener al estado "En formulación" cada vez que se agregue una nueva actividad se mantiene el este estado, al enviar la petición desde el cliente de culminar plan se debe cambiar el estado de plan a "Formulado", la issue debe cumplir con los siguientes requerimientos:

- [x] Se debe crear la información base en el api de pruebas en la tabla de estado_plan
- [x] Desarrollar función para asignación del estado "En formulación"
- [x]  Desarrollar función para asignación del estado "Forrmulado"

**Comment by brayaned** [comment]
Se desarrollaron las tres tareas correspondientes al flujo de estados en el componente de formulación y el api mid de planeación. No se presento ningún problema para la finalización de la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
