### ISSUE TITLE
Ajustes a la función Get y Post para la creación de actividades 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_mid#21]
Se debe realizar los ajustes a las funciones desarrolladas en la issue #19  con los nuevos requerimientos definidos en los dayli, los requerimientos de la issue son:

- [x] Ajustar el método post para que realice el cambio de estado y verificación del estado del plan según la issue #20, 
- [x]  creación de función Put  información en la tabla detalle subgrupo para las observaciones futuras.
- [x] Ajustar método GET para que al recorre los detalles subgrupo si cuentan con alguna observación en un detalle subgrupo se construya el json necesario para ser consumido en el componente dinámico

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by brayaned** [comment]
- Se ajusto el cambio de estado en la función de post del controlador  formulación. No se presento ningún problema mayor para el desarrollo de la tarea.

**Comment by brayaned** [comment]
- Se creó la función GuardarPbservacion() para poder realizar el guardado de la observaciones futuras en el campo observación dentro de cada una de las actividades.

**Comment by brayaned** [comment]
- Se ajustó de manera satisfactoria el get para cada actividad para que al momento de llamar la función desde el cliente esta tenga en cuenta las observaciones que tiene cada actividad.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
