### ISSUE TITLE
Función Put y Delete para las actividades registradas en un plan de trabajo y ajuste de función POST y Get 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_mid#24]
Se debe realizar la creación de las funciones put y delete para las actividades registradas en un plan de trabajo asignado, para esto se debe primero ajustar la función post realizada en la issue #21 , pues se debe incluir un parámetro adicional para cada actividad con el campo "Activo: true", con este campo se debe crear un método que desactive todos los detalles subgrugos registrados en un plan a una actividad particular, en cuanto en la función get se debe actualizar teniendo en cuenta el campo activo, si esta activo trae todos los detalles subgrupo activos y los false no, finalmente se debe crear la función PUT la cual actualiza todos los detalles subgrupos de una actividad particular. la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar la función post para asignar el campo activo en true en todos los detalles subgrupos de una actividad-
- [x] Ajustar la función get desarrollada para que solo traiga los detalles subgrupos de una actividad con campo activo en true 
- [x] Crear función delete que cambien todos los detalles subgrupos el campo activo a false de una actividad particular 
- [x] Crear función Put que actualice los detalles subgrupo de una actividad particulas

**Comment by brayaned** [comment]
Se da inicio a la issue.

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
