### ISSUE TITLE
Ajustes por bandera para consulta de tabla resumen de las actividades 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_mid#29]
Se debe realizar los diferentes ajustes para incluir la bandera que permite definir los campos en la tabla resumen de los planes de acción de inversión, la issue debe cumplir con los siguientes requerimientos:
 

- [x]  Ajustar api de planes_crud con campo bandera_tabla en el esquema sub_grupo, se debe ajustar el api en controladores y modelos, ajustar la [documentación ](https://drive.google.com/drive/u/0/folders/1c8D_loVhPNwqYO7-KF80RYvi9e5N7pNE)
- [x] Ajustar método post para la construcción plan con el nuevo campo establecido 
- [x] Ajustar método get en el modulo construcción de planes para la consulta con el  nuevo campo creado
- [x] Ajustar el cliente con el select de Bandera Tabla resumen, este solo se visualizara cuando sea al menos un segundo nivel
- [x] Ajustar el método de clonar para tener en cuenta esa bandera y ajustar la asignación del estado del plan en formulación.

**Comment by ndmc98** [comment]
Se genera Pull Request para el CRUD con la adición del campo bandera_tabla

**Comment by ndmc98** [comment]
Se ajusta el método clonar para el campo bandera y la asignación del estado del plan. Se genera el Pull Request del MID

**Comment by fabianbarreto02** [comment]
Se da por finalizado la issue
